# Generated by Django 5.1.2 on 2024-10-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_articulo_categoria_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(default='Sin categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='post.categoria'),
        ),
    ]
